Hello World


In [1]:
import numpy as np

In [2]:
a = np.array([1., 2., 3.])

In [3]:
a.dtype, a.shape

(dtype('float64'), (3,))

In [4]:
a.shape

(3,)

In [5]:
b = np.empty((1,2, 3), dtype=int)
b

array([[[-5764607523034234880, -5764607523034234880,
               35871566856197],
        [ 5572452859464646656,                    0,
                            0]]])

In [6]:
new_arr_arang = np.arange(1, 7).astype(float)
new_arr_arang

array([1., 2., 3., 4., 5., 6.])

In [7]:
new_arr_linspace = np.linspace(0, 1, 10)
new_arr_linspace

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Working with random numbers in `numpy`

In [8]:
rng = np.random.default_rng()

In [9]:
b = rng.integers(0, 10, 10, endpoint=True)
b

array([ 0,  5,  4,  8,  1,  9,  8,  5, 10,  6])

In [10]:
rng.standard_normal(3)

array([-0.24718641, -0.41377327, -2.01944222])

In [11]:
b[::-1]

array([ 6, 10,  5,  8,  9,  1,  8,  4,  5,  0])

In [12]:
c = b[:]
c

array([ 0,  5,  4,  8,  1,  9,  8,  5, 10,  6])

In [13]:
b[0] = 13
c

array([13,  5,  4,  8,  1,  9,  8,  5, 10,  6])

In [14]:
n = b[b>8]
n

array([13,  9, 10])

In [15]:
b[b>7]=0
n

array([13,  9, 10])

In [16]:
b

array([0, 5, 4, 0, 1, 0, 0, 5, 0, 6])

In [17]:
n

array([13,  9, 10])

In [18]:
b[(b>4) | (b<2)]=1
b

array([1, 1, 4, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.where(b<=1)

(array([0, 1, 3, 4, 5, 6, 7, 8, 9]),)

In [20]:
b.max() # finds the maximum value within array b

4

In [21]:
b.argmax() # finds the index of teh maximum value in b

2

## All close

In [22]:
np.allclose(1e-9, 2e-9, atol=1e-17)

False

# Numpy for 2D arrays

In [91]:
a = np.array([[1,2,3],[4,5,6]]).astype(float)

In [92]:
a.dtype

dtype('float64')

In [93]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [94]:
# Random number generator for matrix

rng = np.random.default_rng()

In [96]:
x = rng.uniform(1,10, (2, 3))
x

array([[4.28210824, 4.11335737, 9.48078633],
       [6.47727143, 3.95625782, 4.85600747]])

In [98]:
rng.binomial(0.5,0.3, (2,9))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Row Vectors and Column Vectors

In [25]:
a = np.array([1,2,3,4]).reshape((2, 2))
a

array([[1, 2],
       [3, 4]])

In [27]:
a

array([[1, 2],
       [3, 4]])

In [36]:
b = np.repeat(a, 3, axis=1)
b

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [40]:
c = b.repeat(3, axis=0)
c

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4],
       [3, 3, 3, 4, 4, 4],
       [3, 3, 3, 4, 4, 4]])

## Einestine Sum

In [3]:
a = np.array([[1,2,3],[4,5,6]])
b = np.einsum('ij->i', a)
b

array([ 6, 15])

In [26]:
a = np.array([[1, 1, 1],
              [2, 0, 2],
              [5, 5, 3]])

b = np.array([[0, 1, 0],
              [1, 1, 0],
              [1, 1, 1]])      

In [27]:
np.einsum('ii->i', a)


array([1, 0, 3])

## References

1. [NumPy Illustrated: The Visual Guide to NumPy](https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d)
2. [Visual Intro to Numpy](https://jalammar.github.io/visual-numpy/)
3. [Numpy exercises](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)
4. [Binder notebook for numpy exercises](https://hub.gke2.mybinder.org/user/rougier-numpy-100-hj65g8sm/lab)
5. [Using einestien sum](https://ajcr.net/Basic-guide-to-einsum/)
6. [Einestien summation, Youtube Video](https://www.youtube.com/watch?v=pkVwUVEHmfI)