Hello World


In [1]:
import numpy as np

In [9]:
a = np.array([1., 2., 3.])

In [12]:
a.dtype, a.shape

(dtype('float64'), (3,))

In [11]:
a.shape

(3,)

In [18]:
b = np.empty((1,2, 3), dtype=int)
b

array([[[-6917529027641081856, -6917529027641081856,
                            3],
        [                   0,                    0,
              844424930131968]]])

In [31]:
new_arr_arang = np.arange(1, 7).astype(float)
new_arr_arang

array([1., 2., 3., 4., 5., 6.])

In [42]:
new_arr_linspace = np.linspace(0, 1, 10)
new_arr_linspace

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Working with random numbers in `numpy`

In [43]:
rng = np.random.default_rng()

In [54]:
b = rng.integers(0, 10, 10, endpoint=True)
b

array([ 7,  1,  1, 10,  0,  8,  7,  6,  3,  0])

In [56]:
rng.standard_normal(3)

array([-0.96702159, -0.96880523, -0.06225382])

In [62]:
b[::-1]

array([ 0,  3,  6,  7,  8,  0, 10,  1,  1,  7])

In [63]:
c = b[:]
c

array([ 7,  1,  1, 10,  0,  8,  7,  6,  3,  0])

In [64]:
b[0] = 13
c

array([13,  1,  1, 10,  0,  8,  7,  6,  3,  0])

In [67]:
n = b[b>8]
n

array([13, 10])

In [69]:
b[b>7]=0
n

array([13, 10])

In [70]:
b

array([0, 1, 1, 0, 0, 0, 7, 6, 3, 0])

In [71]:
n

array([13, 10])

In [77]:
b[(b>4) | (b<2)]=1
b

array([1, 1, 1, 1, 1, 1, 1, 1, 3, 1])

In [78]:
np.where(b<=1)

(array([0, 1, 2, 3, 4, 5, 6, 7, 9]),)

In [80]:
b.max() # finds the maximum value within array b

3

In [81]:
b.argmax() # finds the index of teh maximum value in b

8

## All close

In [86]:
np.allclose(1e-9, 2e-9, atol=1e-17)

False

# Numpy for 2D arrays

In [91]:
a = np.array([[1,2,3],[4,5,6]]).astype(float)

In [92]:
a.dtype

dtype('float64')

In [93]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [94]:
# Random number generator for matrix

rng = np.random.default_rng()

In [96]:
x = rng.uniform(1,10, (2, 3))
x

array([[4.28210824, 4.11335737, 9.48078633],
       [6.47727143, 3.95625782, 4.85600747]])

In [98]:
rng.binomial(0.5,0.3, (2,9))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

## References

1. [NumPy Illustrated: The Visual Guide to NumPy](https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d)
2. [Visual Intro to Numpy](https://jalammar.github.io/visual-numpy/)